### ISSUE TITLE
UK house name not supported

### ISSUE THREAD

**Issue by nadha25** [tertek/redcap-address-auto-complete#11]
Some houses in the UK do not have house numbers but have house names ( and sometimes have both). When advanced save is enabled, the Number field remains empty and house name information is "lost". Would it be possible to have the house name saved as an advanced field? Thanks

**Comment by tertek** [comment]
@nadha25 Thank you for reporting this issue/feature request. Unfortunately, I am not able to develop new features at this moment. I may assist if there is someone available to make a PR.

**Comment by tertek** [comment]
No reaction.
Can be reopened anytime.
