### ISSUE TITLE
Addition of GetAddress API

### ISSUE THREAD

**Issue by harpsicord86** [tertek/redcap-address-auto-complete#3]
Hi there,

I've just come across your module for REDCap and it's exactly the kind of thing I'm looking for! Unfortunately, I'm based in the UK but I'd like to recommend the addition of GetAddress to your list of APIs.

GetAddress allows you to query a UK based address via a post code or house number and more! Here's a link to the documentation: https://documentation.getaddress.io/

It meets 2 out of 3 of your criteria.... it is a paid-for service which requires an API Key to work. It would be useful to add to this module but I do understand if there is hesitency.

Thanks

**Comment by tertek** [comment]
Hi there,
Thanks for the contribution.
It looks like we could use /autocomplete to fetch suggestions. The only problem is that suggestions do not include GEO data but instead refer to an ID for a second request to be performed /get so that additional information can be fetched for that specific address.

It should be possible to include this into the module but it would change some things.
Would you like to add a PR?

**Comment by tertek** [comment]
So I have found a way to implement this.
Can you please tell me which of these address elements are relevant in our case:

![image](https://user-images.githubusercontent.com/75415872/148187268-7242b64f-5c0b-4e28-93bb-9861b4aa0d68.png)

![image](https://user-images.githubusercontent.com/75415872/148187311-87338274-0ffc-4a7e-9634-f24f3d97d1b2.png)

**Comment by tertek** [comment]
Added in https://github.com/tertek/redcap-address-auto-complete/pulls?q=is%3Apr+is%3Aclosed

**Comment by harpsicord86** [comment]
Hi @tertek,

So sorry for not getting back to you sooner. Really good news that you found a way to implement this! In terms of your question, the formatted address is the most relevant as it follows the best practice here: https://personal.help.royalmail.com/app/answers/detail/a_id/81/~/how-to-address-your-mail-%28clear-addressing%29

But I would also suggest that line1, line 2, line 3, line 4, locality, town or city, county, and postcode also have relevance too.

Hope this helps and thanks again :-)

**Comment by tertek** [comment]
I have implemented:
- thoroughfare
- building_number
- postcode
- town_or_city

Which matches the information given in your link. Thanks !
