### ISSUE TITLE
New API Source: Slovenia

### ISSUE THREAD

**Issue by xylem69** [tertek/redcap-address-auto-complete#5]
Hi,

I've found an API (JSON) for Slovenia:
https://podatki.gov.si/api/3/action/package_show?id=register-prostorskih-enot

How can I check it if it is compatibile with this module?

regards
LV

**Comment by tertek** [comment]
Is there an API Documentation in English?

**Comment by tertek** [comment]
That is good.
You can check the compatibility through this list: https://github.com/tertek/redcap-address-auto-complete#add-your-api-source
Also I would recommend to have a look in the [sources.json](https://github.com/tertek/redcap-address-auto-complete/blob/main/sources/sources.json) where most of the interface is visible.

**Comment by tertek** [comment]
Closed since no reaction.
Can be opened anytime.
